apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-configmap
  labels:
    app: nextcloud
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  NEXTCLOUD_TRUSTED_DOMAINS: "localhost 127.0.0.1"
